# Package managers {#sec-managers}

## What is the importance of package managers

## Conda environments

What is conda: 

To install conda (the comand), miniconda (the lighter distribution).

For Linux x86_64 machine 

```{bash}
#| eval: false
curl -O https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
```

For Mac (Intel, will also works on M1):

```{bash}
#| eval: false
curl -O https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh
```

Once downloaded, the next step is to run the installation script.

```{bash}
#| eval: false
bash Miniconda3-latest-Linux-x86_64.sh
```

After installation is completed, it is recommended to add the following channels to your conda configuration. Conda channels are... 

```{bash}
#| eval: false
conda config --add channels defaults
conda config --add channels bioconda
conda config --add channels conda-forge
```

After this, conda should be installed, you may need to restart your terminal.

::: {.callout-tip}
A faster implementation of the `conda` command is `mamba`. To install it simply run `conda install mamba` and then every time you will install a program just substitute `conda` for `mamba`
:::

## Package managers for OS

There are several package managers handling general purpose packages and apps. For MacOS the famous one is [Homebrew]() and for Windows several could be used such as [Chocolatey]() and [Scoop](https://scoop.sh/).
