# History {.unnumbered}

## Ed. 0.0.11 (2023-01-19)

- Adding some quarto code annotations!

- New chapter on algorithms

- Add a challenge on genome assembly

- Rendering with Q v.1.3

## Ed. 0.0.10 (2022-12-17)

- Update book with new quarto and extension versions

- Challenge on sequence alignment

- Experimenting new covers

- Some typos cleaning

- Change giscus theme

## Ed. 0.0.9 (2022-09-08)

- Starting the Sanger chapter

- More on Seq. analysis

- Keep history on book and add dates

- Change the cover

- Add new parts and chapters outlines (phylogenetics and metagenomics)

- New challenges on seq analysis solved


## Ed. 0.0.8 (2022-08-29)

- New render w/ Quarto 1.1

- Adding more on sequence analysis

- Including new extension for videos

- Improve some images

- Book has now Giscus to enable discussions

- New info on download genomics data

- New foot page with license and more info
  
## Ed. 0.0.7 (2022-08-19)

- Changes in git chapter
  
- More images in different chapters

- Start using new filters : lightbox for images and nutshell for expandable explanations

- Some images in HPC chapter

- Some outlines in Package manager chapter

- Some paragraphs on the sequence analysis chapter

- Additional challenges

## Ed. 0.0.6 (2022-08-09)

- More updates to CLI chapter.

- Update the Version Control chapter.
  
- Decoupled genome annotation section into separate chapter.

- Add a motif search challenge

- Add cover image

- Many typos corrected.
  
## Ed. 0.0.5 (2022-07-28)

- Update CLI chapter.

- Decoupled Seq analysis and Genomics into separate chapters.

- Chapters were reorganized in its own dirs to make easier navigation. They also were renamed for later easier addition of other chapters.

- New learning features using Quarto callouts. This will hopefully improve learning and enjoy the book.

- Chapters sections will have numbering.
  
## Ed. 0.0.4 (2022-04-24)

- Minor typos and outline for the structural biology section

- Start improving crossreferences

## Ed. 0.0.3 (2022-04-18)

- Citation and reference of the book is now almost complete

## Ed. 0.0.2 (2022-04-17)

- This Ed. includes more information of the book and author

- Adds DOI and Zenodo

- Includes Social commenting

## Ed. 0.0.1 (2022-04-12)

- This preliminary Ed. contains the basic outline of the book

- Contains the first draft solutions to challenges demos
