---
filters:
    - nutshell
    - lightbox
lightbox: auto
---
#  Sequence analysis {#sec-seq-analysis}

>In this chapter we we will consider several biological concepts that appear central to understand the manipulation of biological data.
>
> We are also covering the transition of a biological (organic) information to digital bits.
>
> We will explore some databases in which biological information is stored.


## Biological information

Since the origin, organisms (or molecules) have been the result of different selective processes. An emergent property of successive iterations of survival/decease was the ability of molecules to keep a record of its past in a very stable manner, so that it will pass generation to generation. Although this might not be the first property or molecule to ever exist (see the [:origin of life](https://en.wikipedia.org/wiki/Abiogenesis)), the innovation of organisms to pack information of previous events became so advantageous that almost any form of living organism has this property: that is DNA.


![The different scales of information packed in a biological fashion. Figure adapted from @meneely2017 book showing how *DNA in a eukaryote is packaged with chromosomal proteins to form the much more compact chromatin. Chromatin is then folded into higher-order structures and eventually into the chromosome*](imgs-seqan/chromosome-genes.png){#fig-chromosome}

Almost any living organism harbor DNA in a nucleus or chromosome, which is a very compacted structure that could be actually seen to naked eye in some species. It so arranged or condensed [Fig. @fig-chromosome] that it is the result of multiple compacting strategies.

## The duality of DNA

DNA is an organic molecule of [:nucleic acids](https://en.wikipedia.org/wiki/Nucleic_acid) that is mainly build out of nitrogen-containing compounds ([:nucleobases](https://en.wikipedia.org/wiki/Nucleobase)) or just bases.The four bases are adenine (A), cytosine (C), guanine (G) and (T) and they bind strictly as $A=T$ and $C\equiv{G}$ where each of the lines represents an hydrogen bond.

DNA nitrogenous bases of are arranged in a very compacted helix structure and too much can be understood from its molecular nature. It is of course governed by the physicochemical properties of the atoms, therefore DNA is a physicochemical entity. But those common bricks have also a very beautiful emergent property that comes out from their order (mainly), and that is to keep the instructions that build the organism from which it belongs. These instructions are nothing else than information, which also follow some informational rules. Then DNA is also an informational entity.

![DNA double helix structure and main characteristics. Image adapted from @brown2018 showing the structure with the *sugar–phosphate backbone
of each polynucleotide drawn as a gray ribbon with the base pairs in green* ](imgs-seqan/dna-structure.png){#fig-doublehelix width="50%"}

The description of DNA bases helped the elucidation of the helicoidal structure. The first outstanding feature of the DNA structure was indeed highlighted by Watson and Crick in its famous paper about a subtle mechanism of replication. 

This idea of the duality of the DNA (and of course of other biological molecules) is the source of the study of many bioinformatic fields. But a question remains open: how do capture the informational nature of a DNA sequence so that we end up with a sequential file of characters `ATCGCTATC...`. This is not a trivial questions in fact.


## The central ~~dogma~~ theory of molecular biology extended

So far we have addressed that DNA is a very stable molecule that stores biological (i.e., evolutionary) information, that it could represent a sequential object of characters as in a digital object as well. But how is it that this order has an underlying biological sense? This was a very though question that required the accumulation of many experimental discoveries and the meeting of genetics and molecular biology.

## Sequencing strategies


## Sequencing over time

## Some insights from sequencing genomes

::: {.callout-warning}
# Challenge


How many  complete genomes of *Bacillus subtilis* are there in the NCBI databases?

Count the number of features (genes, CDS, ncRNA, rRNA, etc.) in the genome of *Bacillus subtilis* NCIB 3610 (GCF_002055965.1)

Document each of the steps and how did you end up with the answer. Saving the file with your initials (e.g., CG-activity01.{md,txt,docx})z 

:::

## Biological information databases

## Retrieving data from NCBI

### The manual way

### Entrez direct

### A simple program