on:
  push:
    branches: main
  pull_request:
    branches: main
  # to be able to trigger a manual build
  # workflow_dispatch:

name: quarto-render

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2 # quarto-dev/quarto-actions/install-quarto@v1
        with:
          tinytex: true
          # version: 0.9.105

      # Install any computing dependency you may need, usually either python and Jupyter or R

      - name: Install Python
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install general dependencies
        run: |
          python -m pip install ncbi-genome-download
          python -m pip install jupyter
          python -m pip install jupyter-cache
          
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.0'
         # use-public-rspm: true
          
      - name: Install R libraries
        run: |
          install.packages("remotes")
          install.packages("rmarkdown")
          install.packages("tidyverse")
          install.packages("fs")
          install.packages("ape")
          remotes::install_github("YuLab-SMU/ggtree")
        shell: Rscript {0}
      
      - name: Publish to GitHub Pages (and render)
      uses: quarto-dev/quarto-actions/publish@v2
      with:
        target: gh-pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        
      # - name: Quarto render
      #   uses: quarto-dev/quarto-actions/render@v2
          # with:
          #   to: html

      # - name: Deploy 🚀
      #   # only deploy when push to main
      #   if: github.event_name != 'pull_request'
      #   uses: JamesIves/github-pages-deploy-action@v4
      #   with:
      #     # The branch the action should deploy to.
      #     branch: gh-pages
      #     # The folder the action should deploy. Adapt if you changed in Quarto config
      #     folder: docs
